spring.application.name=dietrecc
server.port=8080
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
ai.api.key=${GROQ_API_KEY}
ai.api.url=https://api.groq.com/openai/v1/chat/completions
ai.api.model=${GROQ_MODEL_ID:llama-3.3-70b-versatile}


